// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchState } from "./MatchState";

export type CreateMatch = { tournament_id: string, team_one_id: string, team_two_id: string, scheduled_match_start: string | null, state: MatchState, number_of_games: number, };
