// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameState } from "./GameState";

export type Game = { _id: string, match_id: string, riot_tournament_code: string | null, riot_match_id: string | null, state: GameState, winning_team_id: string | null, participants: Array<string>, };
