// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export type Player = { _id: string, team_id: string, riot_name: string, riot_puuid: string, discord_name: string | null, role: Role, is_team_captain: boolean, };
