// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Team = { _id: string, tournament_ids: Array<string>, name: string, short_name: string, active: boolean, };
