// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TournamentState } from "./TournamentState";

export type Tournament = { _id: string, riot_id: number, name: string, start_date: string, state: TournamentState, };
