// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TournamentState } from "./TournamentState";

export type UpdateTournament = { start_date: string | null, state: TournamentState | null, };
