// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchState } from './MatchState'

export type UpdateMatch = {
    scheduled_match_start: Date | null
    state: MatchState | null
    number_of_games: number | null
}
