// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateTeam = { name: string, short_name: string, active: boolean, participating_tournament_ids: Array<string>, };
