// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameState } from "./GameState";

export type CreateGame = { series_id: string, winner_id: string | null, blue_side_id: string | null, red_side_id: string | null, state: GameState, start: string | null, riot_match_id: string | null, riot_should_generate_tournament_code: boolean, };
