// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeriesKind } from "./SeriesKind";
import type { SeriesState } from "./SeriesState";
import type { SeriesWinner } from "./SeriesWinner";

export type CreateSeries = { start: string, state: SeriesState, kind: SeriesKind, result: SeriesWinner, drafter_link: string | null, tournament_id: string, team_one_id: string, team_two_id: string, };
