// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export type CreatePlayer = { riot_name: string, discord_name: string | null, role: Role, team_captain: boolean, team_id: string, };
