// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export type FilterPlayerParams = { partial_riot_name: string | null, partial_discord_name: string | null, role: Role | null, team_captain: boolean | null, };
