// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateFilter } from "./DateFilter";
import type { TournamentState } from "./TournamentState";

export type FilterTournamentParams = { partial_name: string | null, start_date: DateFilter | null, end_date: DateFilter | null, state: Array<TournamentState>, };
