// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateFilter } from "./DateFilter";
import type { GameState } from "./GameState";

export type FilterGameParams = { state: GameState | null, start: DateFilter | null, any_side_team_id: string | null, };
