// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateFilter } from "./DateFilter";
import type { SeriesState } from "./SeriesState";

export type FilterSeriesParams = { start: DateFilter | null, state: Array<SeriesState> | null, };
