// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameState } from "./GameState";
import type { Player } from "./Player";
import type { Series } from "./Series";
import type { Team } from "./Team";

export type Game = { id: string, state: GameState, start: string | null, series: Series | null, winner: Team | null, blue_side: Team | null, blue_side_players: Array<Player>, red_side: Team | null, red_side_players: Array<Player>, };
