// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IncludeGameParams = { all: boolean, series: boolean, winner: boolean, blue_side_team: boolean, blue_side_players: boolean, red_side_team: boolean, red_side_players: boolean, riot_all_information: boolean, riot_match_information: boolean, riot_tournament_game_information: boolean, riot_lobby_events: boolean, riot_match_data: boolean, riot_match_timeline: boolean, };
