// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IncludeTeamParams = { all: boolean, tournaments: boolean, players: boolean, series: boolean, };
