// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Game } from "./Game";
import type { Role } from "./Role";
import type { Team } from "./Team";

export type Player = { id: string, riot_name: string, discord_name: string | null, role: Role, team_captain: boolean, team: Team | null, games: Array<Game>, };
