// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Game } from "./Game";
import type { SeriesKind } from "./SeriesKind";
import type { SeriesState } from "./SeriesState";
import type { SeriesWinner } from "./SeriesWinner";
import type { Team } from "./Team";
import type { Tournament } from "./Tournament";

export type Series = { id: string, start: string, state: SeriesState, kind: SeriesKind, result: SeriesWinner, drafter_link: string | null, tournament: Tournament | null, team_one: Team | null, team_two: Team | null, games: Array<Game>, };
