// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Player } from "./Player";
import type { Series } from "./Series";
import type { Tournament } from "./Tournament";

export type Team = { id: string, name: string, short_name: string, active: boolean, tournaments: Array<Tournament>, captains: Array<Player>, players: Array<Player>, series: Array<Series>, };
