// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Series } from "./Series";
import type { Team } from "./Team";
import type { TournamentState } from "./TournamentState";

export type Tournament = { id: string, name: string, start_date: string, end_date: string | null, state: TournamentState, win_team_id: string | null, teams: Array<Team>, series: Array<Series>, };
