// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeriesKind } from "./SeriesKind";
import type { SeriesState } from "./SeriesState";
import type { SeriesWinner } from "./SeriesWinner";

export type UpdateSeries = { start: string | null, state: SeriesState | null, kind: SeriesKind | null, result: SeriesWinner | null, drafter_link: string | null, };
