// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateTeam = { name: string | null, short_name: string | null, active: boolean | null, participating_tournament_ids: Array<string>, };
