// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TournamentState } from "./TournamentState";

export type UpdateTournament = { name: string | null, start_date: string | null, end_date: string | null, state: TournamentState | null, win_team_id: string | null, };
