// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameState } from "./GameState";

export type UpdateGame = { state: GameState | null, start: string | null, riot_match_id: string | null, };
