// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export type UpdatePlayer = { discord_name: string | null, role: Role | null, team_captain: boolean | null, team_id: string | null, };
